[env]
TERM = "xterm-256color"

[scrolling]
history = 100_000
multiplier = 3

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[cursor]
blink_interval = 450
blink_timeout = 3

[cursor.style]
shape = "Beam"
blinking = "Always"

[window]
decorations = "Buttonless"
opacity = 0.8
blur = true
startup_mode = "Windowed"
dynamic_padding = false
option_as_alt = "Both"

[window.dimensions]
columns = 130
lines = 40

[window.padding]
x = 3
y = 3

[font]
size = 20
builtin_box_drawing = false
[font.normal]
family = "DankMono Nerd Font"
style = "Regular"
[font.bold]
family = "DankMono Nerd Font"
style = "Regular"
[font.italic]
family = "DankMono Nerd Font"
style = "Italic"

[keyboard]
bindings = [
  { key = "T", mods = "Command", chars = "\u0002c" },
  { key = "W", mods = "Command", chars = "\u0002&" },
  { key = "Tab", mods = "Control", chars = "\u0002n" },
  { key = "Tab", mods = "Control|Shift", chars = "\u0002p" },
  { key = "[", mods = "Command", chars = "\u0002p" },
  { key = "]", mods = "Command", chars = "\u0002n" },
]

[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/catppuccin-frappe.toml"]
